# Generated by Django 2.1.2 on 2018-11-29 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nome', models.CharField(max_length=35)),
                ('conhecimento_java', models.BooleanField()),
                ('conhecimento_python', models.BooleanField()),
                ('conhecimento_aeromodelismo', models.BooleanField()),
                ('conhecimento_fenomenos', models.BooleanField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
